routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
*/
 
Auth::routes(['register' => true]);

/*
|--------------------------------------------------------------------------
| Dashbord & Options Routes
|--------------------------------------------------------------------------
*/

Route::redirect('/',        '/dashboard', 301);
Route::redirect('/home',    '/dashboard', 301);

Route::get('/dashboard',    'HomeController@index'      )->name('home');
Route::get('/settings',     'SettingController@index'   )->name('settings');
Route::post('/settings',    'SettingController@update'  )->name('update.settings');

/*
|--------------------------------------------------------------------------
| Student & Parent routes
|--------------------------------------------------------------------------
*/

Route::resource('parents',      'ParentController');

Route::resource('students',     'StudentController');

Route::resource('students.paiments',    'PaimentController'  );
Route::resource('students.debts',       'DebtController'     );
Route::resource('students.absents',     'AbsentController'   )->except('show');
Route::resource('students.delays',      'DelayController'    )->except('show');
Route::resource('students.complaints',  'ComplaintController')->except('show');
Route::resource('students.notes',       'NoteController'     )->except('show');

/*
|--------------------------------------------------------------------------
| School elements routes
|--------------------------------------------------------------------------
*/

Route::resource('grades',       'GradeController');
Route::resource('schoolyears',  'SchoolyearController');

Route::resource('classrooms',   'ClassroomController'   );
Route::resource('subjects',     'SubjectController'     )->except('show');

Route::resource('exams',        'ExamController'        );
Route::resource('exams.results','ExamResultController'  )->except('show');
Route::resource('examtypes',    'ExamTypeController'    )->except('show');


/*
|--------------------------------------------------------------------------
|  Group Elements
|--------------------------------------------------------------------------
|*/

Route::resource('groups'         ,'GroupController'       );
Route::resource('groups.courses' ,'CourseController'      )->except(['create','show','edit']);


Route::get('groups/{group}/students','GroupController@addStudents')->name('groups.students.add');
Route::post('groups/{group}/students','GroupController@storeStudents')->name('groups.students.store');




/*
|--------------------------------------------------------------------------
| School Employees & teachers routes
|--------------------------------------------------------------------------
*/

Route::resource('teachers',     'TeacherController');
Route::resource('teachers.salaries',    'TeacherSalaryController')->except('show');


Route::resource('employees',    'EmployeeController');
Route::resource('employees.salaries',    'EmployeeSalaryController')->except('show');



/*
|--------------------------------------------------------------------------
| School providers routs
|--------------------------------------------------------------------------
*/

Route::resource('providers',    'ProviderController');

Route::resource('providers.paiments',    'ProviderPaimentController' );
Route::resource('providers.debts',       'ProviderDebtController'    );

app/Classroom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Classroom extends Model
{
    
    protected $guarded = [];

    use SoftDeletes;

}

app/Http/Controllers/ClassroomController.php
<?php

namespace App\Http\Controllers;

use App\Classroom;
use Illuminate\Http\Request;

class ClassroomController extends Controller
{


    public function __construct()
    {
        $this->middleware('auth');
    }




    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('classrooms.index')->with(['classrooms'=>Classroom::all(['id','name','capacity','created_at','updated_at'])]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('classrooms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {

        $classroom = Classroom::create($this->validateRequest());
        return redirect('classrooms');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Classroom $classroom)
    {
        return view('classrooms.show')->with(['classroom'=>$classroom]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Classroom $classroom)
    {
        return view('classrooms.edit')->with(['classroom'=>$classroom]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Classroom $classroom)
    {
        $classroom->update($this->validateRequest());

        return redirect('classrooms/'.$classroom->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Classroom $classroom)
    {
        $classroom->delete();
    }



    private function validateRequest(){

        return request()->validate([
            'capacity'  => 'required|numeric|min:2|max:50',
            'name'      => 'required|max:100',
        ]);

    }
}

resources/views/classrooms/create.blade.php
@extends('layouts.app')
@section('content')

<div class="p-2">
    <!-- ===== Breadcrumb ===== -->

    <breadcrumb :items="[

        {'name':'classrooms', 'link':'{{ route('classrooms.index') }}' }, 
        {'name':'add', 'link':'' }
    
    ]"></breadcrumb>
</div>

<div class="container p-2">
    

    <div class="border shadow-sm rounded-md">

        
                <div class="bg-gray-100 rounded-md">


        
                    <form-header title="{{_('Add Classroom') }}"></form-header>
        
                </div>  
            
                

            <form action="{{ route('classrooms.store') }}" method="post">

                    <div class="border-t border-b py-8 px-4">

                            @csrf
                    
                            @include('classrooms.form')
                        
                    </div>

                    <div class="py-6 px-5 bg-gray-100 rounded-md text-right flex justify-end">

                        <back-button link="{{ route('classrooms.index') }}" text="{{ _('Back') }}"></back-button>
                        <save-button text="Save"></save-button>
                        
                    </div>

            </form>

        </div>
    
        
</div>

@endsection

resources/views/classrooms/edit.blade.php
@extends('layouts.app')
@section('content')


<div class="p-2">
    <!-- ===== Breadcrumb ===== -->

    <breadcrumb :items="[

        {'name':'classrooms', 'link':'{{ route('classrooms.index') }}' }, 
        {'name':'edit', 'link':'' }
    
    ]"></breadcrumb>
            
</div>

<div class="container p-2">
    

    <div class="border shadow-sm rounded-md">

        
                <div class="bg-gray-100 rounded-md">
                    <form-header title="{{_('Edit Classroom') }}"></form-header>
        
                </div>  
            

            <form action="{{ route('classrooms.update',$classroom) }}" method="post">

                    <div class="border-t border-b py-8 px-4">

                            @csrf
                            @method('PUT')
                            @include('classrooms.form')
                        
                    </div>

                    <div class="py-6 px-5 bg-gray-100 rounded-md text-right flex justify-end">

                        <back-button link="{{ route('classrooms.index') }}" text="{{ _('Back') }}"></back-button>
                        <save-button text="Save"></save-button>
                        
                    </div>

            </form>

        </div>
    
        
    </div>

@endsection

resources/views/classrooms/form.blade.php
<div>

    <div class="flex flex-wrap">

        <!--=== name ===-->

        <div class="w-full md:w-1/2">

            <div class="flex flex-col p-4">
                            
                <label for="name" class="text-md">{{ _('Name') }}</label>
    
                <am-input name="name" type="text" value="{{ $classroom->name ?? old('name') }}"></am-input>
                
                @error('name')
    
                    <alert-error message="{{ $message  }}"></alert-error>
    
                @enderror
    
            </div>

        </div>


        <!--=== capacity ===-->

        <div class="w-full md:w-1/2">

            <div class="flex flex-col p-4">
                            
                <label for="capacity" class="text-md">{{ _('capacity') }}</label>
    
                <am-input name="capacity" type="number" value="{{ $classroom->capacity ?? old('capacity') }}"></am-input>
                
                @error('capacity')
    
                    <alert-error message="{{ $message  }}"></alert-error>
    
                @enderror
    
            </div>

        </div>

    </div>


</div>

resources/views/classrooms/index.blade.php
@extends('layouts.app')
@section('content')

<div class="p-2">
    <!-- ===== Breadcrumb ===== -->

    <breadcrumb :items="[

    {'name':'Classrooms', 'link':'' },

    ]"></breadcrumb>
</div>
 
<div class="container p-2">

        
     
    <div class="flex justify-between py-2 mb-2 rounded items-center">
        <div class="text-2xl text-gray-800 flex">

                <svg class="fill-current text-gray-400 w-10 mx-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 26" fill-rule="evenodd" clip-rule="evenodd">
                    <path d="M6.628 23h-2.628l2.732-4h-6.732v-2h1v-16h22v16h1v2h-6.731l2.731 4h-2.627l-2.736-4h-5.273l-2.736 4zm14.372-20h-18v14h18v-14zm-6 12h4v1h-4v-1zm-8.245-6.074l1.157 4.319-1.099.294-.838-3.126-.974.576-.034-.014-.222-.828 1.801-1.165.209-.056zm3.835.922l1.131-.303.25.932-1.132.303.31 1.155-1.055.282-.31-1.154-1.134.304-.25-.932 1.135-.304-.297-1.106 1.055-.283.297 1.106zm4.509 1.471l-1.099.295-.838-3.127-.975.576-.033-.013-.222-.828 1.8-1.166.209-.056 1.158 4.319zm3.932-2.926l.231.861-2.995.803-.231-.861 2.995-.803zm-.328-1.225l.23.861-2.995.803-.23-.862 2.995-.802z"/>                </svg>
                
                {{_('Classrooms') }}
            
            </div>
            <div class=""> <success-button text="{{ _('Add classroom') }}" link="{{ route('classrooms.create') }}"></success-button> </div>
        </div>

        
        <am-table :items="{{ $classrooms }}" index_link="{{ route('classrooms.index') }}"></am-table>
        
    </div>


@endsection