routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
*/
 
Auth::routes(['register' => true]);

/*
|--------------------------------------------------------------------------
| Dashbord & Options Routes
|--------------------------------------------------------------------------
*/

Route::redirect('/',        '/dashboard', 301);
Route::redirect('/home',    '/dashboard', 301);

Route::get('/dashboard',    'HomeController@index'      )->name('home');
Route::get('/settings',     'SettingController@index'   )->name('settings');
Route::post('/settings',    'SettingController@update'  )->name('update.settings');

/*
|--------------------------------------------------------------------------
| Student & Parent routes
|--------------------------------------------------------------------------
*/

Route::resource('parents',      'ParentController');

Route::resource('students',     'StudentController');

Route::resource('students.paiments',    'PaimentController'  );
Route::resource('students.debts',       'DebtController'     );
Route::resource('students.absents',     'AbsentController'   )->except('show');
Route::resource('students.delays',      'DelayController'    )->except('show');
Route::resource('students.complaints',  'ComplaintController')->except('show');
Route::resource('students.notes',       'NoteController'     )->except('show');

/*
|--------------------------------------------------------------------------
| School elements routes
|--------------------------------------------------------------------------
*/

Route::resource('grades',       'GradeController');
Route::resource('schoolyears',  'SchoolyearController');

Route::resource('classrooms',   'ClassroomController'   );
Route::resource('subjects',     'SubjectController'     )->except('show');

Route::resource('exams',        'ExamController'        );
Route::resource('exams.results','ExamResultController'  )->except('show');
Route::resource('examtypes',    'ExamTypeController'    )->except('show');


/*
|--------------------------------------------------------------------------
|  Group Elements
|--------------------------------------------------------------------------
|*/

Route::resource('groups'         ,'GroupController'       );
Route::resource('groups.courses' ,'CourseController'      )->except(['create','show','edit']);


Route::get('groups/{group}/students','GroupController@addStudents')->name('groups.students.add');
Route::post('groups/{group}/students','GroupController@storeStudents')->name('groups.students.store');




/*
|--------------------------------------------------------------------------
| School Employees & teachers routes
|--------------------------------------------------------------------------
*/

Route::resource('teachers',     'TeacherController');
Route::resource('teachers.salaries',    'TeacherSalaryController')->except('show');


Route::resource('employees',    'EmployeeController');
Route::resource('employees.salaries',    'EmployeeSalaryController')->except('show');



/*
|--------------------------------------------------------------------------
| School providers routs
|--------------------------------------------------------------------------
*/

Route::resource('providers',    'ProviderController');

Route::resource('providers.paiments',    'ProviderPaimentController' );
Route::resource('providers.debts',       'ProviderDebtController'    );

app/Exam.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Exam extends Model
{
    
    use SoftDeletes;
    protected $guarded = [];

    /**
     * 
     * 
     * 
     */

     public function results(){
         return $this->hasMany('App\ExamResult');
     }

    /**
     * 
     * 
     * 
     */

    public function subject(){
        return $this->belongsTo('App\Subject');
    }

    /**
     * 
     * 
     * 
     */

    public function ExamType(){
        return $this->belongsTo('App\ExamType');
    }



}

app/ExamType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ExamType extends Model
{
    use SoftDeletes;
    protected $guarded = [];

    public function exams(){
        return $this->hasMany('App\Exam');
    }
}

app/Http/Controllers/ExamController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Exam;
use App\Grade;
use App\ExamType;
use App\Subject;


class ExamController extends Controller
{


    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('exams.index')->with(['exams'=>Exam::all(['id','name','created_at','updated_at'])]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('exams.create')->with(["exam_types"=>ExamType::all(),"subjects"=>Subject::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $exam = Exam::create($this->validateRequest());
        return redirect('exams/'.$exam->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Exam $exam)
    {
        $results   = $exam->results()->get(['id','mark','student_id']);
        

        foreach ($results as $index=>$result){

            $result->student = $result->student->surname . ' ' . $result->student->name;
            unset($result->student_id);

            
            $results->{$index} = $result;
            
        }
   
       
        return view('exams.show')->with(["exam"=>$exam,"results"=>$results]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Exam $exam)
    {
        return view('exams.edit')->with([

            "exam_types" => ExamType::all(),
            "subjects"   => Subject::all(),
            "exam"       => $exam

        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Exam $exam)
    {
        $exam->update($this->validateRequest());
        return redirect('exams/'.$exam->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Exam $exam)
    {
        $exam->delete();
        
    }

    /**
     * 
     * 
     * 
     */
    private function validateRequest(){
        return request()->validate([
            
                'name'          =>'required|max:100',
                'subject_id'    =>'required|numeric',
                'exam_type_id'  =>'required|numeric',

        ]);
    }
}

resources/views/exams/results/create.blade.php
@extends('layouts.app')
@section('content')

  
<div class="container p-2">
    
    <!-- ===== Breadcrumb ===== -->
        
    <breadcrumb :items="[

        {'name':'{{ $exam->name }}', 'link':'{{ route('exams.results.index',$exam) }}' }, 
        {'name':'results', 'link':'{{ route('exams.results.index',$exam) }}' },
        {'name':'add', 'link':'' }
    
    ]"></breadcrumb>

    

    <div class="border shadow-sm mt-4 rounded-md">

    
        <div class="bg-gray-100 rounded-md">

            <form-header title="{{_('Add Result') }}"></form-header>
            <info-person-bar :person="{{ $exam }}"></info-person-bar>

        </div>  

        <form action="{{ route('exams.results.store',$exam) }}" method="post">

                <div class="border-t border-b py-8 px-4">

                        @csrf
                        
                        @include('exams.results.form')
                    
                </div>

                <div class="py-6 px-5 bg-gray-100 rounded-md text-right flex justify-end">

                    <back-button link="{{ route('exams.results.index',$exam) }}" text="{{ _('Back') }}"></back-button>
                    <save-button text="Save"></save-button>
                    
                </div>
        </form>
    
    </div>


</div>





@endsection

resources/views/exams/results/edit.blade.php
@extends('layouts.app')
@section('content')

  
<div class="container p-2">
    
    <!-- ===== Breadcrumb ===== -->
        
    <breadcrumb :items="[

        {'name':'{{ $exam->name }}', 'link':'{{ route('exams.results.index',$exam) }}' }, 
        {'name':'results', 'link':'{{ route('exams.results.index',$exam) }}' },
        {'name':'edit', 'link':'' }
    
    ]"></breadcrumb>

    

    <div class="border shadow-sm mt-4 rounded-md">

    
        <div class="bg-gray-100 rounded-md">

            <form-header title="{{_('Edit Result') }}"></form-header>
            <info-person-bar :person="{{ $exam }}"></info-person-bar>

        </div>  

        <form action="{{ route('exams.results.update',[$exam,$result]) }}" method="post">

                <div class="border-t border-b py-8 px-4">

                        @csrf
                        @method('PUT')
                        @include('exams.results.form')
                    
                </div>

                <div class="py-6 px-5 bg-gray-100 rounded-md text-right flex justify-end">

                    <back-button link="{{ route('exams.results.index',$exam) }}" text="{{ _('Back') }}"></back-button>
                    <save-button text="Save"></save-button>
                    
                </div>
        </form>
    
    </div>


</div>





@endsection

resources/views/exams/results/form.blade.php
<div>


    <div class="flex flex-wrap">


        <div class="w-full md:w-1/2">
                <div class="flex flex-col p-4 ">
                                    
                    <label for="mark" class="text-md">{{ _('Mark') }}</label>
                    <am-input name="mark" type="number" value="{{ $result->mark ?? old('mark') }}"></am-input>
                    @error('mark')

                        <alert-error message="{{ $message  }}"></alert-error>

                    @enderror

                </div>
        </div>

        <div class="w-full md:w-1/2">
                <div class="flex flex-col p-4 ">
                                    
                    <label for="student" class="text-md">{{ _('Student') }}</label>
                    <drop :items="{{ $students }}" name="student" column_name="student_id" selected={{ $result->student_id ?? old('student_id') }}></drop>
                    @error('student_id')

                        <alert-error message="{{ $message  }}"></alert-error>

                    @enderror

                </div>
        </div>

    </div>



</div>